"""fast_arm's test-only Robot Profile / Runtime Plugin conformance case."""

from __future__ import annotations

from dataclasses import dataclass, replace
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

from xpotato_sim.mujoco_backend.endpoint_extraction import extract_mujoco_site_endpoint_from_state
from xpotato_sim.mujoco_backend.model_info import MuJoCoModelInfo
from xpotato_sim.mujoco_backend.model_loader import load_mujoco_model
from xpotato_sim.mujoco_backend.simulator import HeadlessMuJoCoSimulator
from xpotato_sim.plugins.robots.fast_arm.adapter.kinematics import FastArmMuJoCoModelForwardKinematicsSolver
from xpotato_sim.plugins.robots.fast_arm.adapter.model_contract import FAST_ARM_TIP_SITE_NAME
from xpotato_sim.plugins.robots.fast_arm.adapter.feasibility import (
    load_and_validate_fast_arm_joint_limit_config,
)
from xpotato_sim.plugins.robots.fast_arm.adapter.profile import FAST_ARM_ROBOT_PROFILE
from xpotato_sim.plugins.robots.fast_arm.adapter.runtime import FAST_ARM_RUNTIME_PLUGIN
from xpotato_sim.runtime.composition.robot_plugin import validate_profile_model_dimensions
from xpotato_sim.runtime.composition.robot_resolution import validate_robot_profile_plugin_consistency
from xpotato_sim.schemas import MuJoCoState
from tests.support.robot_runtime_plugin_conformance import (
    FailClosedCase,
    InverseKinematicsRoundTripCase,
    KnownForwardKinematicsCase,
    MuJoCoEndpointConsistencyCase,
    RobotRuntimePluginConformanceCase,
)


HOME_QPOS = (0.0, -0.5235987755982989, 0.0, -1.0471975511965976)
NONTRIVIAL_QPOS_A = (0.2, -0.9, 0.35, -0.45)
NONTRIVIAL_QPOS_B = (-0.35, -1.15, -0.25, 0.6)

FAST_ARM_KNOWN_FK_CASES = (
    KnownForwardKinematicsCase(
        case_id="canonical_home",
        qpos=HOME_QPOS,
        expected_endpoint_m=(0.4330127018922193, 0.0, -0.48),
        coordinate_frame="fast_arm endpoint solver frame",
        unit="meter",
        tolerance_m=1e-9,
        provenance="Authoring-time literal from the documented closed-form endpoint calculation; not generated by the tested FK solver at test execution.",
    ),
    KnownForwardKinematicsCase(
        case_id="multiple_joint_nontrivial_pose",
        qpos=NONTRIVIAL_QPOS_A,
        expected_endpoint_m=(0.480716783278594, 0.0974461162080186, -0.5226482579523202),
        coordinate_frame="fast_arm endpoint solver frame",
        unit="meter",
        tolerance_m=1e-9,
        provenance="Authoring-time literal from the documented closed-form endpoint calculation at a multi-joint qpos; not generated by the tested FK solver at test execution.",
    ),
)

FAST_ARM_IK_ROUND_TRIP_CASES = (
    InverseKinematicsRoundTripCase(
        case_id="reachable_solver_frame_pose_a",
        target_position_m=(0.394420683283742, 0.0, -0.6142738189097645),
        seed_qpos=(0.0, -1.0, 0.0, 0.0),
        coordinate_frame="fast_arm endpoint solver frame",
        unit="meter",
        tolerance_m=1e-5,
    ),
    InverseKinematicsRoundTripCase(
        case_id="reachable_solver_frame_pose_b",
        target_position_m=(0.3242351128933894, 0.04900334448929833, -0.6435835452301163),
        seed_qpos=(0.0, -1.0, 0.0, 0.0),
        coordinate_frame="fast_arm endpoint solver frame",
        unit="meter",
        tolerance_m=1e-5,
    ),
)

FAST_ARM_MUJOCO_ENDPOINT_CASES = (
    MuJoCoEndpointConsistencyCase(
        case_id="canonical_home_site",
        qpos=HOME_QPOS,
        coordinate_frame="MuJoCo world / scene frame",
        unit="meter",
        tolerance_m=1e-9,
    ),
    MuJoCoEndpointConsistencyCase(
        case_id="multiple_joint_nontrivial_site",
        qpos=NONTRIVIAL_QPOS_B,
        coordinate_frame="MuJoCo world / scene frame",
        unit="meter",
        tolerance_m=1e-9,
    ),
)


@dataclass(frozen=True, slots=True)
class _ProfilePluginProjection:
    profile: object

    @property
    def profile_id(self) -> str:
        return self.profile.profile_id


def _failure_plugin_id_mismatch(_tmp_path: Path) -> None:
    mismatch = replace(FAST_ARM_ROBOT_PROFILE, profile_id="different-profile")
    validate_robot_profile_plugin_consistency(
        FAST_ARM_ROBOT_PROFILE.profile_id,
        FAST_ARM_ROBOT_PROFILE,
        _ProfilePluginProjection(mismatch),
    )


def _failure_profile_declaration_mismatch(_tmp_path: Path) -> None:
    mismatch = replace(FAST_ARM_ROBOT_PROFILE, model_contract_version="different-model/v1")
    validate_robot_profile_plugin_consistency(
        FAST_ARM_ROBOT_PROFILE.profile_id,
        FAST_ARM_ROBOT_PROFILE,
        _ProfilePluginProjection(mismatch),
    )


def _failure_qpos_dimension_mismatch(_tmp_path: Path) -> None:
    validate_profile_model_dimensions(
        FAST_ARM_ROBOT_PROFILE,
        SimpleNamespace(nq=FAST_ARM_ROBOT_PROFILE.qpos_dimension + 1, nv=FAST_ARM_ROBOT_PROFILE.qvel_dimension),
    )


def _failure_qvel_dimension_mismatch(_tmp_path: Path) -> None:
    validate_profile_model_dimensions(
        FAST_ARM_ROBOT_PROFILE,
        SimpleNamespace(nq=FAST_ARM_ROBOT_PROFILE.qpos_dimension, nv=FAST_ARM_ROBOT_PROFILE.qvel_dimension + 1),
    )


def _failure_joint_order_mismatch(_tmp_path: Path) -> None:
    wrong_order = tuple(reversed(FAST_ARM_ROBOT_PROFILE.canonical_joint_names))
    info = MuJoCoModelInfo(joint_names=wrong_order, body_names=(), site_names=())
    model = SimpleNamespace(nq=4, nv=4)
    with patch(
        "xpotato_sim.plugins.robots.fast_arm.adapter.runtime.inspect_mujoco_model",
        return_value=info,
    ):
        with patch(
            "xpotato_sim.plugins.robots.fast_arm.adapter.runtime."
            "validate_fast_arm_model_name_contract"
        ):
            FAST_ARM_RUNTIME_PLUGIN.validate_model(model)


def _failure_missing_endpoint_site(_tmp_path: Path) -> None:
    extract_mujoco_site_endpoint_from_state(
        MuJoCoState(frame_index=0, time_s=0.0),
        site_name=FAST_ARM_TIP_SITE_NAME,
    )


def _failure_missing_home_keyframe(_tmp_path: Path) -> None:
    load_mujoco_model(
        FAST_ARM_ROBOT_PROFILE.mujoco_model_asset,
        initial_keyframe_name="missing-home-keyframe",
    )


def _failure_home_outside_joint_limits(tmp_path: Path) -> None:
    source = FAST_ARM_ROBOT_PROFILE.joint_limit_config_asset
    if source is None:
        raise AssertionError("fast_arm conformance case requires a joint-limit config")
    from xpotato_sim.runtime.composition.robot_resource import read_package_resource_bytes

    text = read_package_resource_bytes(source).decode("utf-8")
    invalid = text.replace(
        "[joints.elbow_joint]\nlower_rad = -3.141592653589793\nupper_rad = 3.141592653589793",
        "[joints.elbow_joint]\nlower_rad = -0.5\nupper_rad = 0.5",
    )
    path = tmp_path / "invalid-home-limits.toml"
    path.write_text(invalid, encoding="utf-8", newline="\n")
    simulator = HeadlessMuJoCoSimulator.from_model_path(
        FAST_ARM_ROBOT_PROFILE.mujoco_model_asset,
        initial_keyframe_name=FAST_ARM_ROBOT_PROFILE.initial_keyframe_name,
    )
    load_and_validate_fast_arm_joint_limit_config(path, model=simulator.model)


FAST_ARM_FAIL_CLOSED_CASES = (
    FailClosedCase(
        case_id="plugin_identity_mismatch",
        description="requested profile ID and plugin ID must agree",
        run=_failure_plugin_id_mismatch,
        exception_type=ValueError,
        message_pattern="plugin registry identity mismatch",
    ),
    FailClosedCase(
        case_id="profile_declaration_mismatch",
        description="profile and plugin declarative contracts must agree",
        run=_failure_profile_declaration_mismatch,
        exception_type=ValueError,
        message_pattern="model contract version mismatch",
    ),
    FailClosedCase(
        case_id="qpos_dimension_mismatch",
        description="model qpos dimension must match the profile",
        run=_failure_qpos_dimension_mismatch,
        exception_type=ValueError,
        message_pattern="qpos dimension mismatch",
    ),
    FailClosedCase(
        case_id="qvel_dimension_mismatch",
        description="model qvel dimension must match the profile",
        run=_failure_qvel_dimension_mismatch,
        exception_type=ValueError,
        message_pattern="qvel dimension mismatch",
    ),
    FailClosedCase(
        case_id="joint_order_mismatch",
        description="model joint order must match the profile",
        run=_failure_joint_order_mismatch,
        exception_type=ValueError,
        message_pattern="joint order mismatch",
    ),
    FailClosedCase(
        case_id="missing_endpoint_site",
        description="the declared endpoint site must not fall back silently",
        run=_failure_missing_endpoint_site,
        exception_type=ValueError,
        message_pattern="missing site name 'tip'",
    ),
    FailClosedCase(
        case_id="missing_home_keyframe",
        description="the declared home keyframe must exist",
        run=_failure_missing_home_keyframe,
        exception_type=ValueError,
        message_pattern="configured initial keyframe is missing",
    ),
    FailClosedCase(
        case_id="home_outside_joint_limits",
        description="the profile-owned home pose must satisfy its joint-limit config",
        run=_failure_home_outside_joint_limits,
        exception_type=ValueError,
        message_pattern="home qpos",
    ),
)


FAST_ARM_ROBOT_RUNTIME_PLUGIN_CONFORMANCE_CASE = RobotRuntimePluginConformanceCase(
    case_id="fast_arm",
    expected_profile_id=FAST_ARM_ROBOT_PROFILE.profile_id,
    profile=FAST_ARM_ROBOT_PROFILE,
    plugin=FAST_ARM_RUNTIME_PLUGIN,
    model_asset=FAST_ARM_ROBOT_PROFILE.mujoco_model_asset,
    home_keyframe_name=FAST_ARM_ROBOT_PROFILE.initial_keyframe_name,
    expected_joint_names=FAST_ARM_ROBOT_PROFILE.canonical_joint_names,
    expected_qpos_dimension=4,
    expected_qvel_dimension=4,
    endpoint_site_name=FAST_ARM_TIP_SITE_NAME,
    joint_limit_config_asset=FAST_ARM_ROBOT_PROFILE.joint_limit_config_asset,
    known_fk_cases=FAST_ARM_KNOWN_FK_CASES,
    ik_round_trip_cases=FAST_ARM_IK_ROUND_TRIP_CASES,
    mujoco_endpoint_cases=FAST_ARM_MUJOCO_ENDPOINT_CASES,
    fail_closed_cases=FAST_ARM_FAIL_CLOSED_CASES,
    model_aligned_endpoint_evaluator=FastArmMuJoCoModelForwardKinematicsSolver().forward,
)


__all__ = ["FAST_ARM_ROBOT_RUNTIME_PLUGIN_CONFORMANCE_CASE"]
