import assert from "node:assert/strict";
import {canConnect, createWorkbenchGamepadMessages, preparationIsCurrent} from "../src/app/workbenchLifecycle.js";
import {exportedHeapBytes} from "../src/wasm-scene/exportedHeap.js";
import {sampleViewerGamepadSnapshot, buildViewerGamepadControlMessage} from "../src/input/gamepadInput.js";

const a={readyState:0}, b={readyState:1};
assert.equal(canConnect(a),false);
assert.equal(canConnect(b),false);
assert.equal(canConnect({readyState:3}),true);
const load={socket:a,epoch:"a",generation:1};
const status={ticket:{epoch:"a"},generation:1,busy:null};
assert.equal(preparationIsCurrent(load,a,status),true);
assert.equal(preparationIsCurrent(load,b,status),false);
assert.equal(preparationIsCurrent(load,a,{...status,generation:2}),false);
assert.equal(preparationIsCurrent(load,a,{...status,ticket:{epoch:"b"}}),false);
assert.equal(preparationIsCurrent(load,a,{...status,busy:"stop"}),false);

let getterCalls=0;
const emscripten=Object.defineProperty({},"HEAPU8",{get(){getterCalls++;throw new Error("ABORT");}});
assert.equal(exportedHeapBytes(emscripten),null);
assert.equal(getterCalls,0);
assert.equal(exportedHeapBytes({}),null);
assert.equal(exportedHeapBytes({HEAPU8:new Uint8Array(128)}),128);

const sample=sampleViewerGamepadSnapshot([{connected:true,index:0,id:"test-pad",axes:[.05,-.6],buttons:[{pressed:true,value:.7}]}]);
const wire=buildViewerGamepadControlMessage(sample,12,{sequence:0,metadata:{viewer_provider_session_id:"trial-a"}});
assert.deepEqual(wire.gamepad?.raw_axes,[.05,-.6]);
assert.equal(wire.gamepad?.axes[0],0);
assert.equal(wire.gamepad?.buttons[0].value,.7);
assert.equal(wire.metadata?.viewer_provider_session_id,"trial-a");
const disconnected=buildViewerGamepadControlMessage(sampleViewerGamepadSnapshot(null),13);
assert.equal(disconnected.gamepad?.connected,false);
assert.equal(disconnected.gamepad?.stale,true);
assert.deepEqual(disconnected.gamepad?.axes,[]);
let sessions=0;
const acquire=createWorkbenchGamepadMessages(()=>`session-${++sessions}`);
const pads=[{connected:true,axes:[.05,-.6],buttons:[{pressed:true,value:.7}]}];
assert.equal(acquire("one",null,1),null,"初回欠測を中立sampleへ置き換えない");
const first=acquire("one",pads,2)!;
assert.deepEqual(first.gamepad?.raw_axes,[.05,-.6]);
assert.equal(first.sequence,0);
assert.equal(acquire("one",pads,3)?.sequence,1);
const lost=acquire("one",null,4)!;
assert.equal(lost.gamepad?.stale,true);
assert.equal(lost.gamepad?.connected,false);
assert.equal(lost.metadata?.viewer_provider_session_id,first.metadata?.viewer_provider_session_id);
assert.equal(acquire("two",null,5),null);
const second=acquire("two",pads,6)!;
assert.equal(second.sequence,0);
assert.notEqual(second.metadata?.viewer_provider_session_id,first.metadata?.viewer_provider_session_id);
console.log("Workbench socket/epoch, safe heap and raw input checks passed");
